test gitaction lint and sphinx build

diff --git a/.github/workflows/python-app.yaml b/.github/workflows/python-app.yaml
--- a/.github/workflows/python-app.yaml
+++ b/.github/workflows/python-app.yaml
@@ -1,6 +1,8 @@
 name: Python Tests
 
 on:
+  push:
+    branches: [ documentation ]
   pull_request:
     branches: [ main, dev ]
 
@@ -25,16 +27,38 @@ jobs:
       run: |
         poetry install
 
-    - name: Run unit tests
-      run: |
-        poetry run pytest -m "not slow" --cov=esce --cov-report=term 
+    # - name: Run unit tests
+    #   run: |
+    #     poetry run pytest -m "not slow" --cov=esce --cov-report=term 
 
-    - name: Run snakemake workflow test
-      run: |
-        poetry run snakemake -F -c1 --configfile tests/test_config.yaml
+    # - name: Run snakemake workflow test
+    #   run: |
+    #     poetry run snakemake -F -c1 --configfile tests/test_config.yaml
 
     # - name: Run snakemake submodule test (slow)
     #   run: |
     #     export GITHUB_TOKEN=${{ github.token }}
     #     poetry run snakemake -s tests/snakefile_submodule -c1 -F --use-conda --conda-frontend conda
-        
+
+    ## Alternatively: normal linting, stop the build if there are Python syntax errors       
+    - name: Lint with flake8
+      run: |
+        pip install flake8==4.0.1
+        flake8 . --count --select=E9,F63,F7 --show-source --statistics
+        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+
+    - name: Build documentation
+      run: |
+        pip install sphinx>=1.8 sphinx_rtd_theme sphinx-copybutton piccolo-theme
+        # conda list
+        # sphinx-build -M html docs docs/build -qW
+        # sphinx-build -M html docs docs/build -Eqn -b coverage
+        sphinx-build -v -b html docs/ docs/_build/
+        if [[ -s docs/build/html/python.txt ]]
+        then
+          echo
+          echo "Error: Documentation missing:"
+          echo
+          cat docs/build/html/python.txt
+          exit 1
